#!/usr/bin/python
import urllib2
import subprocess
import time
from evdev import InputDevice, ecodes
with open('/home/blake/excursion/yassine/deamon/scannereventfilename.txt') as fevent:
	ss=fevent.read().splitlines()[0]
	#print(ss)
#quit()
dev = InputDevice(ss)
#print(dev)
rfid = ""
for event in dev.read_loop():
	if event.type == ecodes.EV_KEY and not(event.value):
		rfid += ecodes.KEY[event.code][-1]
		if rfid[-1] == 'R': 
			rfid = rfid[:-1]
			#get rfid status from aws server
			try:
				data = urllib2.urlopen("https://www.excursionclub.info/api/memberRFIDcheck/"+rfid).getcode()
			#except urllib2.HTTPError:
			#	data = 401
			#	pass 
				print(data)
				print("good RFID!!")
				if data == 200:
					with open("/home/blake/excursion/yassine/gatelogs/gate.log", "a") as f:
						f.write(time.strftime("%Y-%m-%d %H:%M:%S")+" "+rfid+"\n")
					subprocess.call(['/home/blake/excursion/yassine/powerUSBdevice/executable/pwrusbcmd', '0', '0', '1'])
					subprocess.call(['sleep', '5'])
					subprocess.call(['/home/blake/excursion/yassine/powerUSBdevice/executable/pwrusbcmd', '0', '0', '0'])
			except:
				print("BADDD rfid")
				with open("/home/blake/excursion/yassine/gatelogs/gate.log", "a") as f:
					 f.write(time.strftime("%Y-%m-%d %H:%M:%S")+" tag "+rfid+" not in system\n")
			rfid = ""
